# Generated by Django 3.2.18 on 2023-03-19 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230319_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 12, 23, 12, 907891)),
        ),
    ]
